Добавлена Кафка в CI

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -21,6 +21,10 @@ jobs:
     runs-on: ubuntu-24.04
 
     services:
+      kafka:
+        image: apache/kafka:4.3.1
+        ports:
+          - 9092:9092
       postgres:
         image: postgres:15.2
 
@@ -58,12 +62,52 @@ jobs:
       - name: Check Chrome
         run: google-chrome --version
 
+      - name: Create Kafka topic
+        env:
+          KAFKA_CONTAINER: ${{ job.services.kafka.id }}
+        run: |
+          echo "Waiting for Kafka..."
+
+          for i in {1..30}; do
+            if timeout 10s docker exec "$KAFKA_CONTAINER" \
+              /opt/kafka/bin/kafka-topics.sh \
+              --bootstrap-server localhost:9092 \
+              --list > /dev/null 2>&1; then
+              echo "Kafka is ready"
+              break
+            fi
+
+            if [ "$i" -eq 30 ]; then
+              echo "Kafka failed to start"
+              docker logs "$KAFKA_CONTAINER" --tail 100
+              exit 1
+            fi
+
+            sleep 2
+          done
+
+          docker exec "$KAFKA_CONTAINER" \
+            /opt/kafka/bin/kafka-topics.sh \
+            --bootstrap-server localhost:9092 \
+            --create \
+            --if-not-exists \
+            --topic payment-events \
+            --partitions 3 \
+            --replication-factor 1
+
+          docker exec "$KAFKA_CONTAINER" \
+            /opt/kafka/bin/kafka-topics.sh \
+            --bootstrap-server localhost:9092 \
+            --describe \
+            --topic payment-events
+
       - name: Start payments backend
         working-directory: backend
         env:
           SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/paymentsdb
           SPRING_DATASOURCE_USERNAME: postgres
           SPRING_DATASOURCE_PASSWORD: postgres
+          SPRING_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
         run: |
           nohup mvn --batch-mode spring-boot:run > ../backend.log 2>&1 &
           echo $! > ../backend.pid
@@ -92,9 +136,11 @@ jobs:
             -DuiUrl=http://localhost:8080 \
             -DdbUrl=jdbc:postgresql://localhost:5432/paymentsdb \
             -DdbUser=postgres \
-            -DdbPassword=postgres
+            -DdbPassword=postgres \
+            -DkafkaBootstrapServers=localhost:9092
 
       - name: Generate Allure report
+        if: always()
         run: mvn --batch-mode allure:report
 
       - name: Upload test artifacts
